/**
 * Created by polaris on 8/9/17.
 */
import '/imports/api/activityMessages/server/publications';
import '/imports/api/bankCredentials/server/publications';
// import '/imports/api/braintree/server/publications';
import '/imports/api/clientApps/server/publications';
import '/imports/api/companies/server/publications';
import '/imports/api/contracts/server/publications';
import '/imports/api/contractsStatusChanges/server/publications';
import '/imports/api/conversations/server/publications';
import '/imports/api/countries/server/publications';
import '/imports/api/entryTags/server/publications';
// import '/imports/api/future-tasks/server/publications';
// import '../../api/google-services/server/publications';
import '/imports/api/industries/server/publications';
import '/imports/api/jobCategories/server/publications';
import '/imports/api/jobPerks/server/publications';
import '/imports/api/jobs/server/publications';
import '/imports/api/jobTypes/server/publications';
import '/imports/api/leads/server/publications';
import '/imports/api/messages/server/publications';
import '/imports/api/notifications/server/publications';
import '/imports/api/positions/server/publications';
import '/imports/api/projects/server/publications';
import '/imports/api/screenRecords/server/publications';
import '/imports/api/screenShots/server/publications';
import '/imports/api/skills/server/publications';
import '/imports/api/tasks/server/publications';
import '/imports/api/teams/server/publications';
import '/imports/api/timeEntries/server/publications';
import '/imports/api/tools/server/publications';
import '/imports/api/transactions/server/publications';
import '/imports/api/userEducations/server/publications';
import '/imports/api/userPortfolioProjects/server/publications';
import '/imports/api/users/server/publications';
import '/imports/api/userWorkExperience/server/publications';
// import '/imports/api/webrtc/server/publications';
import '/imports/api/workPlaces/server/publications';


import '/imports/api/activityMessages/methods';
import '/imports/api/bankCredentials/methods';
import '/imports/api/braintree/server/methods';
import '/imports/api/clientApps/methods';
import '/imports/api/companies/methods';
import '/imports/api/contracts/methods';
import '/imports/api/contractsStatusChanges/methods';
import '/imports/api/conversations/methods';
import '/imports/api/countries/methods';
import '/imports/api/entryTags/methods';
import '/imports/api/google-services/server/google-api/methods';
import '/imports/api/industries/methods';
import '/imports/api/jobCategories/methods';
import '/imports/api/jobPerks/methods';
import '/imports/api/jobs/methods';
import '/imports/api/jobTypes/methods';
import '/imports/api/leads/methods';
import '/imports/api/messages/methods';
import '/imports/api/notifications/methods';
import '/imports/api/positions/methods';
import '/imports/api/projects/methods';
import '/imports/api/screenRecords/methods';
import '/imports/api/screenShots/methods';
import '/imports/api/skills/methods';
import '/imports/api/tasks/methods';
import '/imports/api/teams/methods';
import '/imports/api/timeEntries/methods';
import '/imports/api/tools/methods';
import '/imports/api/transactions/methods';
import '/imports/api/userEducations/methods';
import '/imports/api/userPortfolioProjects/methods';
import '/imports/api/users/methods';
import '/imports/api/userWorkExperience/methods';
// import '/imports/api/webrtc/methods';
import '/imports/api/workPlaces/methods';
